In [1]:
import json
import pandas as pd

with open('data/videos/20200507-033205_climate_change.json') as json_file:
    data = json.load(json_file)

In [2]:
ids = [list(d.keys())[0] for d in data]
flat_data = []
for unique_id in ids:
    flat = dict(data[ids.index(unique_id)][unique_id])
    flat['id'] = unique_id
    flat['recommendations'] = len(flat['recommendations'])
    flat_data.append(flat)
flat_data = pd.DataFrame(flat_data)

In [3]:
top25 = flat_data[['title','id','channel','genre','key']].groupby(['title','channel','genre','id']).count().sort_values(by='key',ascending=False).head(25)

In [7]:
# export Data.Frame
top25.to_csv(r'./data/top25/20200507-033205_climate_change_top25.csv', header=True)

FileNotFoundError: [Errno 2] No such file or directory: 'data/top25/20200507-033205_climate_change_top25.csv'

In [5]:
top25

                                                                                                                     key
title                                              channel                        genre                 id
ðŸ”´ Al Jazeera English | Live                        Al Jazeera English             News & Politics       30qZjexZ8bQ   54
The Discipline of Finishing: Conor Neill at TED... TEDx Talks                     Nonprofits & Activism zXCiv4sc5eY   30
The Day the Mesozoic Died: The Asteroid That Ki... biointeractive                 Science & Technology  tRPu5u_Pizk   29
NASA Live: Official Stream of NASA TV              NASA                           Science & Technology  21X5lGlDOfg   28
The mathematics of weight loss | Ruben Meerman ... TEDx Talks                     Nonprofits & Activism vuIlsN32WaE   27
The Napoleonic Wars (PARTS 1-6)                    Epic History TV                Education             91OmO2YMiDM   25
SpaceX Starship at Voyager Station:Station Cons... The Gateway Foundation         Science & Technology  hJ6wwA9wXog   24
Is China facing a global backlash against coron... Al Jazeera English             News & Politics       SPWiUJzyYno   24
Al Jazeera Arabic Live Stream HD- Ø§Ù„Ø¨Ø« Ø§Ù„Ø­ÙŠ Ù„Ù‚Ù†... Al Jazeera Arabic Ù‚Ù†Ø§Ø© Ø§Ù„Ø¬Ø²ÙŠØ±Ø© News & Politics       _LH87G8buEM   24
Frank Abagnale: "Catch Me If You Can" | Talks a... Talks at Google                People & Blogs        vsMydMDi3rI   23
Life in North Korea | DW Documentary               DW Documentary                 Education             StjIv33zJ9c   23
Watch Full Coronavirus Coverage - May 6 | NBC N... NBC News                       News & Politics       N_ESahO0r9s   22
1918 Spanish Flu historical documentary | Swine... Chromosome8                    People & Blogs        UDY5COg2P2c   20
Master Shi Heng Yi â€“ 5 hindrances to self-maste... TEDx Talks                     Nonprofits & Activism 4-079YIasck   19
Money, happiness and eternal life - Greed (dire... DW Documentary                 Education             CVuVlk2E_e4   18
The Space Shuttle (Narrated by William Shatner)    NASA                           Science & Technology  SvaG0xDdP8g   18
The Skill of Humor | Andrew Tarvin | TEDxTAMU      TEDx Talks                     Nonprofits & Activism MdZAMSyn_As   18
Soyuz undocking, reentry and landing explained     European Space Agency, ESA     Science & Technology  -l7MM9yoxII   17
Shenzhen: The Silicon Valley of Hardware (Full ... WIRED UK                       Science & Technology  SGJ5cZnoodY   17
Visiting North Korea | DW Documentary              DW Documentary                 Education             reEZn3mJ-Fo   17
The Year of Pluto - New Horizons Documentary Br... NASA                           Science & Technology  EJxwWpaGoJs   16
History of Russia (PARTS 1-5) - Rurik to Revolu... Epic History TV                Education             w0Wmc8C0Eq0   16
2. The Bronze Age Collapse - Mediterranean Apoc... Fall of Civilizations          Education             B965f8AcNbw   15
Alexander the Great (All Parts)                    Epic History TV                Education             K7lb6KWBanI   15
1000 AD: A Tour of the Viking World // Vikings ... History Time                   Education             G3_iLTpTYhY   15

In [8]:
#top25 videos weight
top25['key'].sum() / len(flat_data)

0.4815513626834382

In [11]:
#top25 average - number of videos per unique video
top25['key'].sum() / 25

367.52

In [12]:
top25_channel = flat_data[['channel','key']].groupby(['channel']).count().sort_values(by='key',ascending=False).head(25)

In [13]:
top25_channel

                              key
channel
Fox News                     4284
LastWeekTonight              1731
MSNBC                        1670
NBC News                     1522
CNBC Television              1016
Global News                   770
ITV News                      708
The Sun                       611
Yahoo Finance                 394
TIME                          378
Guardian News                 315
PBS NewsHour                  307
USA TODAY                     306
HooverInstitution             212
TheEllenShow                  210
Valuetainment                 185
CNBC                          184
The Obama White House         164
Reagan Library                162
The Eric Metaxas Radio Show   133
NowThis News                  129
CBC News                      110
Democracy Now!                110
The Hill                      107
Wendover Productions          100

In [14]:
#top25_channel channel weight
top25_channel['key'].sum() / len(flat_data)

0.8290356394129978

In [15]:
#top25 average - number of videos per unique video
top25_channel['key'].sum() / 25

632.72

In [16]:
#top25 by genre
top25_genre = flat_data[['genre','key']].groupby(['genre']).count().sort_values(by='key',ascending=False).head(25)

In [17]:
top25_genre

                         key
genre
News & Politics        14387
Entertainment           2319
Education                848
People & Blogs           377
Film & Animation         257
Howto & Style            222
Comedy                   144
Music                     95
Travel & Events           93
Nonprofits & Activism     91
Science & Technology      81
Sports                    52
Autos & Vehicles          28
Gaming                    22

In [18]:
#top25_genre genre weight
top25_genre['key'].sum() / len(flat_data)

0.9966457023060796